/**
 * @author Brandon Kalinowski
 * @copyright 2020 Brandon Kalinowski
 * @license Not Provided. Contact for details.
 */
// *** WARNING: this file was generated by the Kite Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as kite from 'https://deno.land/x/lib/kite.ts'

/**
 * Provides a DigitalOcean domain resource.
 *
 * > This content is derived from https://github.com/terraform-providers/terraform-provider-digitalocean/blob/master/website/docs/r/domain.html.markdown.
 */
export class Domain extends kite.Resource {
	/**
	 * The IP address of the domain. If specified, this IP
	 * is used to created an initial A record for the domain.
	 */
	public readonly ipAddress!: string | undefined
	/**
	 * The name of the domain
	 */
	public readonly name!: string
	/**
	 * The uniform resource name of the domain
	 */
	public readonly /*out*/ urn!: string

	/**
	 * Create a Domain resource with the given unique name, arguments, and options.
	 *
	 * @param name The _unique_ name of the resource.
	 * @param args The arguments to use to populate this resource's properties.
	 */
	constructor(name: string, args: DomainArgs) {
		let inputs: any = {}
		if (!args || args.name === undefined) {
			throw new Error("Missing required property 'name'")
		}
		inputs.ipAddress = args ? args.ipAddress : undefined
		inputs.name = args ? args.name : undefined
		super(name, inputs)
		this.setType(Domain.__kiteType)
		this.urn = `(( tf ${this.id()}.urn ))` as any /*out*/
	}
	/**
	 * Used to map camelCased properties to Terraform snake_case
	 * @internal
	 */
	static convertMap: Record<string, string> = {
		ipAddress: 'ip_address',
		name: 'name',
		urn: 'undefined',
	}

	/**
	 * Transforms the Resource instance into the Terraform JSON representation.
	 * @internal
	 */
	convert() {
		const props: any = {}
		Object.entries(this).forEach(([key, value]) => {
			const newKey = Domain.convertMap[key]
			if (!newKey) {
				throw new Error(
					`Could not print key: ${key}. Not found in ${
						(this as any).__type
					} spec.`
				)
			}
			if (newKey !== 'undefined' /* out */) {
				props[newKey] = value
			}
		})
		return {
			terraform: {
				required_providers: {
					digitalocean: '~> 1.13.0',
				},
			},
			resource: {
				digitalocean_domain: { [this.__name]: props },
			},
		}
	}

	/** @internal */
	public static readonly __kiteType = 'tf:digitalocean:index/domain:Domain'
	/** @internal */
	public static readonly __tfType = 'digitalocean_domain'

	/** @internal */
	public id() {
		return Domain.__tfType + '.' + this.__name
	}
}

/**
 * The set of arguments for constructing a Domain resource.
 */
export interface DomainArgs {
	/**
	 * The IP address of the domain. If specified, this IP
	 * is used to created an initial A record for the domain.
	 */
	readonly ipAddress?: string
	/**
	 * The name of the domain
	 */
	readonly name: string
}
