/**
 * @author Brandon Kalinowski
 * @copyright 2020 Brandon Kalinowski
 * @license Not Provided. Contact for details.
 */
// *** WARNING: this file was generated by the Kite Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as kite from 'https://deno.land/x/lib/kite.ts'

/**
 * Provides a resource for assigning an existing DigitalOcean Floating IP to a Droplet. This
 * makes it easy to provision floating IP addresses that are not tied to the lifecycle of your
 * Droplet.
 *
 * > This content is derived from https://github.com/terraform-providers/terraform-provider-digitalocean/blob/master/website/docs/r/floating_ip_assignment.html.markdown.
 */
export class FloatingIpAssignment extends kite.Resource {
	/**
	 * The ID of Droplet that the Floating IP will be assigned to.
	 */
	public readonly dropletId!: number
	/**
	 * The Floating IP to assign to the Droplet.
	 */
	public readonly ipAddress!: string

	/**
	 * Create a FloatingIpAssignment resource with the given unique name, arguments, and options.
	 *
	 * @param name The _unique_ name of the resource.
	 * @param args The arguments to use to populate this resource's properties.
	 */
	constructor(name: string, args: FloatingIpAssignmentArgs) {
		let inputs: any = {}
		if (!args || args.dropletId === undefined) {
			throw new Error("Missing required property 'dropletId'")
		}
		if (!args || args.ipAddress === undefined) {
			throw new Error("Missing required property 'ipAddress'")
		}
		inputs.dropletId = args ? args.dropletId : undefined
		inputs.ipAddress = args ? args.ipAddress : undefined
		super(name, inputs)
		this.setType(FloatingIpAssignment.__kiteType)
	}
	/**
	 * Used to map camelCased properties to Terraform snake_case
	 * @internal
	 */
	static convertMap: Record<string, string> = {
		dropletId: 'droplet_id',
		ipAddress: 'ip_address',
	}

	/**
	 * Transforms the Resource instance into the Terraform JSON representation.
	 * @internal
	 */
	convert() {
		const props: any = {}
		Object.entries(this).forEach(([key, value]) => {
			const newKey = FloatingIpAssignment.convertMap[key]
			if (!newKey) {
				throw new Error(
					`Could not print key: ${key}. Not found in ${
						(this as any).__type
					} spec.`
				)
			}
			if (newKey !== 'undefined' /* out */) {
				props[newKey] = value
			}
		})
		return {
			terraform: {
				required_providers: {
					digitalocean: '~> 1.13.0',
				},
			},
			resource: {
				digitalocean_floating_ip_assignment: { [this.__name]: props },
			},
		}
	}

	/** @internal */
	public static readonly __kiteType =
		'tf:digitalocean:index/floatingIpAssignment:FloatingIpAssignment'
	/** @internal */
	public static readonly __tfType = 'digitalocean_floating_ip_assignment'

	/** @internal */
	public id() {
		return FloatingIpAssignment.__tfType + '.' + this.__name
	}
}

/**
 * The set of arguments for constructing a FloatingIpAssignment resource.
 */
export interface FloatingIpAssignmentArgs {
	/**
	 * The ID of Droplet that the Floating IP will be assigned to.
	 */
	readonly dropletId: number
	/**
	 * The Floating IP to assign to the Droplet.
	 */
	readonly ipAddress: string
}
