/**
 * @author Brandon Kalinowski
 * @copyright 2020 Brandon Kalinowski
 * @license Not Provided. Contact for details.
 */
// *** WARNING: this file was generated by the Kite Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as kite from 'https://deno.land/x/lib/kite.ts'

/**
 * Provides a DigitalOcean Floating IP to represent a publicly-accessible static IP addresses that can be mapped to one of your Droplets.
 *
 * > **NOTE:** Floating IPs can be assigned to a Droplet either directly on the `digitalocean.FloatingIp` resource by setting a `dropletId` or using the `digitalocean.FloatingIpAssignment` resource, but the two cannot be used together.
 *
 * > This content is derived from https://github.com/terraform-providers/terraform-provider-digitalocean/blob/master/website/docs/r/floating_ip.html.markdown.
 */
export class FloatingIp extends kite.Resource {
	/**
	 * The ID of Droplet that the Floating IP will be assigned to.
	 */
	public readonly dropletId!: number | undefined
	/**
	 * The IP Address of the resource
	 */
	public readonly ipAddress!: string
	/**
	 * The region that the Floating IP is reserved to.
	 */
	public readonly region!: string
	/**
	 * The uniform resource name of the floating ip
	 */
	public readonly /*out*/ urn!: string

	/**
	 * Create a FloatingIp resource with the given unique name, arguments, and options.
	 *
	 * @param name The _unique_ name of the resource.
	 * @param args The arguments to use to populate this resource's properties.
	 */
	constructor(name: string, args: FloatingIpArgs) {
		let inputs: any = {}
		if (!args || args.region === undefined) {
			throw new Error("Missing required property 'region'")
		}
		inputs.dropletId = args ? args.dropletId : undefined
		inputs.ipAddress = args ? args.ipAddress : undefined
		inputs.region = args ? args.region : undefined
		super(name, inputs)
		this.setType(FloatingIp.__kiteType)
		this.urn = `(( tf ${this.id()}.urn ))` as any /*out*/
	}
	/**
	 * Used to map camelCased properties to Terraform snake_case
	 * @internal
	 */
	static convertMap: Record<string, string> = {
		dropletId: 'droplet_id',
		ipAddress: 'ip_address',
		region: 'region',
		urn: 'undefined',
	}

	/**
	 * Transforms the Resource instance into the Terraform JSON representation.
	 * @internal
	 */
	convert() {
		const props: any = {}
		Object.entries(this).forEach(([key, value]) => {
			const newKey = FloatingIp.convertMap[key]
			if (!newKey) {
				throw new Error(
					`Could not print key: ${key}. Not found in ${
						(this as any).__type
					} spec.`
				)
			}
			if (newKey !== 'undefined' /* out */) {
				props[newKey] = value
			}
		})
		return {
			terraform: {
				required_providers: {
					digitalocean: '~> 1.13.0',
				},
			},
			resource: {
				digitalocean_floating_ip: { [this.__name]: props },
			},
		}
	}

	/** @internal */
	public static readonly __kiteType =
		'tf:digitalocean:index/floatingIp:FloatingIp'
	/** @internal */
	public static readonly __tfType = 'digitalocean_floating_ip'

	/** @internal */
	public id() {
		return FloatingIp.__tfType + '.' + this.__name
	}
}

/**
 * The set of arguments for constructing a FloatingIp resource.
 */
export interface FloatingIpArgs {
	/**
	 * The ID of Droplet that the Floating IP will be assigned to.
	 */
	readonly dropletId?: number
	/**
	 * The IP Address of the resource
	 */
	readonly ipAddress?: string
	/**
	 * The region that the Floating IP is reserved to.
	 */
	readonly region: string
}
