/**
 * @author Brandon Kalinowski
 * @copyright 2020 Brandon Kalinowski
 * @license Not Provided. Contact for details.
 */
// *** WARNING: this file was generated by the Kite Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as kite from 'https://deno.land/x/lib/kite.ts'

/**
 * The provider type for the digitalocean package. By default, resources use package-wide configuration
 * settings, however an explicit `Provider` instance may be created and passed during resource
 * construction to achieve fine-grained programmatic control over provider settings. See the
 * [documentation](https://www.pulumi.com/docs/reference/programming-model/#providers) for more information.
 *
 * > This content is derived from https://github.com/terraform-providers/terraform-provider-digitalocean/blob/master/website/docs/index.html.markdown.
 */
export class Provider extends kite.Resource {
	/**
	 * Create a Provider resource with the given unique name, arguments, and options.
	 *
	 * @param name The _unique_ name of the resource.
	 * @param args The arguments to use to populate this resource's properties.
	 */
	constructor(name: string, args?: ProviderArgs) {
		let inputs: any = {}
		inputs.apiEndpoint = args ? args.apiEndpoint : undefined
		inputs.spacesAccessId = args ? args.spacesAccessId : undefined
		inputs.spacesSecretKey = args ? args.spacesSecretKey : undefined
		inputs.token = args ? args.token : undefined
		super(name, inputs)
		this.setType(Provider.__kiteType)
	}
	/**
	 * Used to map camelCased properties to Terraform snake_case
	 * @internal
	 */
	static convertMap: Record<string, string> = {
		apiEndpoint: 'api_endpoint',
		spacesAccessId: 'spaces_access_id',
		spacesSecretKey: 'spaces_secret_key',
		token: 'token',
	}

	/**
	 * Transforms the Resource instance into the Terraform JSON representation.
	 * @internal
	 */
	convert() {
		const props: any = {}
		Object.entries(this).forEach(([key, value]) => {
			const newKey = Provider.convertMap[key]
			if (!newKey) {
				throw new Error(
					`Could not print key: ${key}. Not found in ${
						(this as any).__type
					} spec.`
				)
			}
			if (newKey !== 'undefined' /* out */) {
				props[newKey] = value
			}
		})
		return {
			terraform: {
				required_providers: {
					digitalocean: '~> 1.13.0',
				},
			},
			provider: {
				digitalocean: props,
			},
		}
	}

	/** @internal */
	public static readonly __kiteType = 'tf:digitalocean'
	/** @internal */
	public static readonly __tfType = ''

	/** @internal */
	public id() {
		return Provider.__tfType + '.' + this.__name
	}
}

/**
 * The set of arguments for constructing a Provider resource.
 */
export interface ProviderArgs {
	/**
	 * The URL to use for the DigitalOcean API.
	 */
	readonly apiEndpoint?: string
	/**
	 * The access key ID for Spaces API operations.
	 */
	readonly spacesAccessId?: string
	/**
	 * The secret access key for Spaces API operations.
	 */
	readonly spacesSecretKey?: string
	/**
	 * The token key for API operations.
	 */
	readonly token?: string
}
