/**
 * @author Brandon Kalinowski
 * @copyright 2020 Brandon Kalinowski
 * @license Not Provided. Contact for details.
 */
// *** WARNING: this file was generated by the Kite Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as kite from 'https://deno.land/x/lib/kite.ts'

/**
 * Provides a DigitalOcean SSH key resource to allow you to manage SSH
 * keys for Droplet access. Keys created with this resource
 * can be referenced in your Droplet configuration via their ID or
 * fingerprint.
 *
 * > This content is derived from https://github.com/terraform-providers/terraform-provider-digitalocean/blob/master/website/docs/r/ssh_key.html.markdown.
 */
export class SshKey extends kite.Resource {
	/**
	 * The fingerprint of the SSH key
	 */
	public readonly /*out*/ fingerprint!: string
	/**
	 * The name of the SSH key for identification
	 */
	public readonly name!: string
	/**
	 * The public key. If this is a file, it
	 * can be read using the file interpolation function
	 */
	public readonly publicKey!: string

	/**
	 * Create a SshKey resource with the given unique name, arguments, and options.
	 *
	 * @param name The _unique_ name of the resource.
	 * @param args The arguments to use to populate this resource's properties.
	 */
	constructor(name: string, args: SshKeyArgs) {
		let inputs: any = {}
		if (!args || args.publicKey === undefined) {
			throw new Error("Missing required property 'publicKey'")
		}
		inputs.name = args ? args.name : undefined
		inputs.publicKey = args ? args.publicKey : undefined
		super(name, inputs)
		this.setType(SshKey.__kiteType)
		this.fingerprint = `(( tf ${this.id()}.fingerprint ))` as any /*out*/
	}
	/**
	 * Used to map camelCased properties to Terraform snake_case
	 * @internal
	 */
	static convertMap: Record<string, string> = {
		name: 'name',
		publicKey: 'public_key',
		fingerprint: 'undefined',
	}

	/**
	 * Transforms the Resource instance into the Terraform JSON representation.
	 * @internal
	 */
	convert() {
		const props: any = {}
		Object.entries(this).forEach(([key, value]) => {
			const newKey = SshKey.convertMap[key]
			if (!newKey) {
				throw new Error(
					`Could not print key: ${key}. Not found in ${
						(this as any).__type
					} spec.`
				)
			}
			if (newKey !== 'undefined' /* out */) {
				props[newKey] = value
			}
		})
		return {
			terraform: {
				required_providers: {
					digitalocean: '~> 1.13.0',
				},
			},
			resource: {
				digitalocean_ssh_key: { [this.__name]: props },
			},
		}
	}

	/** @internal */
	public static readonly __kiteType = 'tf:digitalocean:index/sshKey:SshKey'
	/** @internal */
	public static readonly __tfType = 'digitalocean_ssh_key'

	/** @internal */
	public id() {
		return SshKey.__tfType + '.' + this.__name
	}
}

/**
 * The set of arguments for constructing a SshKey resource.
 */
export interface SshKeyArgs {
	/**
	 * The name of the SSH key for identification
	 */
	readonly name?: string
	/**
	 * The public key. If this is a file, it
	 * can be read using the file interpolation function
	 */
	readonly publicKey: string
}
