/**
 * @author Brandon Kalinowski
 * @copyright 2020 Brandon Kalinowski
 * @license Not Provided. Contact for details.
 */
// *** WARNING: this file was generated by the Kite Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as kite from 'https://deno.land/x/lib/kite.ts'

/**
 * Provides a DigitalOcean Tag resource. A Tag is a label that can be applied to a
 * Droplet resource in order to better organize or facilitate the lookups and
 * actions on it. Tags created with this resource can be referenced in your Droplet
 * configuration via their ID or name.
 *
 * > This content is derived from https://github.com/terraform-providers/terraform-provider-digitalocean/blob/master/website/docs/r/tag.html.markdown.
 */
export class Tag extends kite.Resource {
	/**
	 * The name of the tag
	 */
	public readonly name!: string

	/**
	 * Create a Tag resource with the given unique name, arguments, and options.
	 *
	 * @param name The _unique_ name of the resource.
	 * @param args The arguments to use to populate this resource's properties.
	 */
	constructor(name: string, args?: TagArgs) {
		let inputs: any = {}
		inputs.name = args ? args.name : undefined
		super(name, inputs)
		this.setType(Tag.__kiteType)
	}
	/**
	 * Used to map camelCased properties to Terraform snake_case
	 * @internal
	 */
	static convertMap: Record<string, string> = {
		name: 'name',
	}

	/**
	 * Transforms the Resource instance into the Terraform JSON representation.
	 * @internal
	 */
	convert() {
		const props: any = {}
		Object.entries(this).forEach(([key, value]) => {
			const newKey = Tag.convertMap[key]
			if (!newKey) {
				throw new Error(
					`Could not print key: ${key}. Not found in ${
						(this as any).__type
					} spec.`
				)
			}
			if (newKey !== 'undefined' /* out */) {
				props[newKey] = value
			}
		})
		return {
			terraform: {
				required_providers: {
					digitalocean: '~> 1.13.0',
				},
			},
			resource: {
				digitalocean_tag: { [this.__name]: props },
			},
		}
	}

	/** @internal */
	public static readonly __kiteType = 'tf:digitalocean:index/tag:Tag'
	/** @internal */
	public static readonly __tfType = 'digitalocean_tag'

	/** @internal */
	public id() {
		return Tag.__tfType + '.' + this.__name
	}
}

/**
 * The set of arguments for constructing a Tag resource.
 */
export interface TagArgs {
	/**
	 * The name of the tag
	 */
	readonly name?: string
}
