/**
 * @author Brandon Kalinowski
 * @copyright 2020 Brandon Kalinowski
 * @license Not Provided. Contact for details.
 */
// *** WARNING: this file was generated by the Kite Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as kite from 'https://deno.land/x/lib/kite.ts'

/**
 * Manages attaching a Volume to a Droplet.
 *
 * > **NOTE:** Volumes can be attached either directly on the `digitalocean.Droplet` resource, or using the `digitalocean.VolumeAttachment` resource - but the two cannot be used together. If both are used against the same Droplet, the volume attachments will constantly drift.
 *
 * > This content is derived from https://github.com/terraform-providers/terraform-provider-digitalocean/blob/master/website/docs/r/volume_attachment.html.markdown.
 */
export class VolumeAttachment extends kite.Resource {
	/**
	 * ID of the Droplet to attach the volume to.
	 */
	public readonly dropletId!: number
	/**
	 * ID of the Volume to be attached to the Droplet.
	 */
	public readonly volumeId!: string

	/**
	 * Create a VolumeAttachment resource with the given unique name, arguments, and options.
	 *
	 * @param name The _unique_ name of the resource.
	 * @param args The arguments to use to populate this resource's properties.
	 */
	constructor(name: string, args: VolumeAttachmentArgs) {
		let inputs: any = {}
		if (!args || args.dropletId === undefined) {
			throw new Error("Missing required property 'dropletId'")
		}
		if (!args || args.volumeId === undefined) {
			throw new Error("Missing required property 'volumeId'")
		}
		inputs.dropletId = args ? args.dropletId : undefined
		inputs.volumeId = args ? args.volumeId : undefined
		super(name, inputs)
		this.setType(VolumeAttachment.__kiteType)
	}
	/**
	 * Used to map camelCased properties to Terraform snake_case
	 * @internal
	 */
	static convertMap: Record<string, string> = {
		dropletId: 'droplet_id',
		volumeId: 'volume_id',
	}

	/**
	 * Transforms the Resource instance into the Terraform JSON representation.
	 * @internal
	 */
	convert() {
		const props: any = {}
		Object.entries(this).forEach(([key, value]) => {
			const newKey = VolumeAttachment.convertMap[key]
			if (!newKey) {
				throw new Error(
					`Could not print key: ${key}. Not found in ${
						(this as any).__type
					} spec.`
				)
			}
			if (newKey !== 'undefined' /* out */) {
				props[newKey] = value
			}
		})
		return {
			terraform: {
				required_providers: {
					digitalocean: '~> 1.13.0',
				},
			},
			resource: {
				digitalocean_volume_attachment: { [this.__name]: props },
			},
		}
	}

	/** @internal */
	public static readonly __kiteType =
		'tf:digitalocean:index/volumeAttachment:VolumeAttachment'
	/** @internal */
	public static readonly __tfType = 'digitalocean_volume_attachment'

	/** @internal */
	public id() {
		return VolumeAttachment.__tfType + '.' + this.__name
	}
}

/**
 * The set of arguments for constructing a VolumeAttachment resource.
 */
export interface VolumeAttachmentArgs {
	/**
	 * ID of the Droplet to attach the volume to.
	 */
	readonly dropletId: number
	/**
	 * ID of the Volume to be attached to the Droplet.
	 */
	readonly volumeId: string
}
