/**
 * @author Brandon Kalinowski
 * @copyright 2020 Brandon Kalinowski
 * @license Not Provided. Contact for details.
 */
// *** WARNING: this file was generated by the Kite Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

export interface CertRequestSubject {
	commonName?: string
	country?: string
	locality?: string
	organization?: string
	organizationalUnit?: string
	postalCode?: string
	province?: string
	serialNumber?: string
	streetAddresses?: string[]
}

export interface SelfSignedCertSubject {
	commonName?: string
	country?: string
	locality?: string
	organization?: string
	organizationalUnit?: string
	postalCode?: string
	province?: string
	serialNumber?: string
	streetAddresses?: string[]
}
